# Generated by Django 4.1.7 on 2023-02-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='phone_number',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
