# Generated by Django 4.1.7 on 2023-02-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_utilisateur_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='age',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='dateEmbauche',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='dateInscription',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
