# Generated by Django 4.1.7 on 2023-03-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_remove_utilisateur_age_utilisateur_dateembauche_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='id',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code',
            field=models.UUIDField(default=None, primary_key=True, serialize=False),
        ),
    ]
