# Generated by Django 4.1.7 on 2023-03-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_remove_utilisateur_id_utilisateur_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='isPasswordSet',
            field=models.BooleanField(default=None),
        ),
    ]
