# Generated by Django 4.1.7 on 2023-03-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_utilisateur_ispasswordset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='isPasswordSet',
            field=models.BooleanField(default=True),
        ),
    ]
